package main

import (
	"fmt"
	"os"
	"runtime"
	"strings"
	"time"
)

// ── Markdown export ───────────────────────────────────────────────────────────

// benchCase groups a pair of results (pread vs uring) for the same config.
type benchCase struct {
	Mode      AccessMode
	BlockSize int
	QD        int
	Pread     *RunResult // nil if not run
	Uring     *RunResult // nil if not run/available
}

func exportMarkdown(
	outPath string,
	fileSize int64,
	dataFile string,
	directIO bool,
	passes int,
	cases []benchCase,
	storage *StorageInfo,
) error {
	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("create output: %w", err)
	}
	defer f.Close()

	p := func(format string, args ...any) {
		fmt.Fprintf(f, format+"\n", args...)
	}

	uringOK, uringFeats := probeIOUring()

	p("# io_uring vs pread – Read Performance Comparison")
	p("")
	p("## Test Environment")
	p("")
	p("| Parameter | Value |")
	p("|-----------|-------|")
	p("| Date | %s |", time.Now().Format("2006-01-02 15:04:05"))
	p("| OS | %s |", runtime.GOOS)
	p("| Architecture | %s |", runtime.GOARCH)
	p("| Kernel | %s |", kernelVersion())
	p("| Data File | `%s` |", dataFile)
	p("| File Size | %.0f MB |", float64(fileSize)/(1024*1024))
	ioMode := "buffered"
	if directIO {
		ioMode = directIOMethod()
	}
	p("| I/O Mode | %s |", ioMode)
	p("| Workload | entire file per pass |")
	p("| Passes | %d |", passes)
	if uringOK {
		p("| io_uring features | %s |", ioUringFeaturesString(uringFeats))
	} else {
		p("| io_uring | not available |")
	}
	if storage != nil {
		p("| Storage Device | %s (`%s`) |", storage.Model, storage.Device)
		p("| Interface | %s |", storage.Interface())
		if storage.Firmware != "" {
			p("| Firmware | %s |", storage.Firmware)
		}
	}
	p("")

	// Group cases by (mode, block size) for side-by-side QD sweep tables.
	type groupKey struct {
		mode AccessMode
		bs   int
	}
	groups := make(map[groupKey][]benchCase)
	var groupOrder []groupKey
	for _, c := range cases {
		key := groupKey{mode: c.Mode, bs: c.BlockSize}
		if _, exists := groups[key]; !exists {
			groupOrder = append(groupOrder, key)
		}
		groups[key] = append(groups[key], c)
	}

	for _, key := range groupOrder {
		cs := groups[key]
		modeStr := key.mode.String()
		title := strings.ToUpper(modeStr[:1]) + modeStr[1:]
		p("## %s Read – %s blocks", title, fmtSize(key.bs))
		p("")
		writeComparisonTable(p, cs)
		p("")
		writeComparisonObservations(p, cs)
		p("")
	}

	// ── Summary: where io_uring helps most ─────────────────────────────
	p("## Summary")
	p("")
	writeSummary(p, cases)

	p("")
	p("## Methodology")
	p("")
	p("1. **Identical workload**: both engines receive the same pre-generated offset")
	p("   sequence (deterministic RNG, same seed), so each read touches the same")
	p("   blocks in the same order.  Each pass reads the entire file once")
	p("   (`fileSize / blockSize` I/O operations).")
	p("2. **Page cache drop**: the page cache is dropped before each run to")
	p("   ensure reads hit the storage device.")
	p("3. **pread engine**: a pool of QD goroutines issues concurrent `pread(2)`")
	p("   calls against a shared file descriptor.")
	p("4. **io_uring engine**: a single goroutine manages the submission/completion")
	p("   rings, keeping QD requests in-flight.  `IORING_OP_READ` (kernel 5.6+)")
	p("   is used instead of the older vectored `IORING_OP_READV`.")
	p("5. **Latency**: per-I/O latency is measured from submission to completion.")
	p("   For pread this is the `ReadAt` wall time; for io_uring it is from")
	p("   SQE preparation to CQE reaping.")
	p("6. **CPU accounting**: `getrusage(RUSAGE_SELF)` captures process-wide")
	p("   user + system CPU time and voluntary/involuntary context switches.")
	p("7. **Aggregation**: when multiple passes are requested, latency samples")
	p("   are pooled.")
	p("")
	p("---")
	p("")
	p("*Generated by [bench/disk/readcmp](https://github.com/rjl493456442/bench)*")

	return nil
}

// writeComparisonTable emits a side-by-side table for a set of QD values.
func writeComparisonTable(p func(string, ...any), cases []benchCase) {
	hasUring := false
	for _, c := range cases {
		if c.Uring != nil {
			hasUring = true
			break
		}
	}

	if !hasUring {
		// Pread-only table.
		p("| QD | Throughput | IOPS | Avg Lat | P50 | P95 | P99 | P99.9 | CPU/op | CtxSw |")
		p("|---:|-----------:|-----:|--------:|----:|----:|----:|------:|-------:|------:|")
		for _, c := range cases {
			r := c.Pread
			if r == nil {
				continue
			}
			p("| %d | %.2f MB/s | %s | %s | %s | %s | %s | %s | %s | %d |",
				c.QD, r.ThroughputMBps(), fmtFloat(r.IOPS()),
				fmtDuration(r.AvgLat()), fmtDuration(r.Pct(50)),
				fmtDuration(r.Pct(95)), fmtDuration(r.Pct(99)),
				fmtDuration(r.Pct(99.9)), fmtDuration(r.CPUPerOp()),
				r.VolCtxSw+r.InvolCtxSw)
		}
		return
	}

	p("| QD | Engine | Throughput | IOPS | Avg Lat | P50 | P95 | P99 | P99.9 | CPU/op | CtxSw | Errors |")
	p("|---:|-------:|-----------:|-----:|--------:|----:|----:|----:|------:|-------:|------:|-------:|")
	for _, c := range cases {
		for _, r := range []*RunResult{c.Pread, c.Uring} {
			if r == nil {
				continue
			}
			p("| %d | %s | %.2f MB/s | %s | %s | %s | %s | %s | %s | %s | %d | %d |",
				c.QD, r.EngineName, r.ThroughputMBps(), fmtFloat(r.IOPS()),
				fmtDuration(r.AvgLat()), fmtDuration(r.Pct(50)),
				fmtDuration(r.Pct(95)), fmtDuration(r.Pct(99)),
				fmtDuration(r.Pct(99.9)), fmtDuration(r.CPUPerOp()),
				r.VolCtxSw+r.InvolCtxSw, r.Errors)
		}
	}
}

func writeComparisonObservations(p func(string, ...any), cases []benchCase) {
	p("### Observations")
	p("")

	for _, c := range cases {
		if c.Pread == nil || c.Uring == nil {
			continue
		}
		pr, ur := c.Pread, c.Uring
		iopsRatio := ur.IOPS() / pr.IOPS()
		latRatio := float64(pr.AvgLat()) / float64(ur.AvgLat())
		ctxPr := pr.VolCtxSw + pr.InvolCtxSw
		ctxUr := ur.VolCtxSw + ur.InvolCtxSw

		winner := "uring"
		if iopsRatio < 1.0 {
			winner = "pread"
			iopsRatio = 1.0 / iopsRatio
		}

		p("- **QD=%d**: %s achieves **%.2fx** IOPS advantage (%.0f vs %.0f). "+
			"Average latency ratio pread/uring = **%.2f**. Context switches: pread=%d, uring=%d.",
			c.QD, winner, iopsRatio, ur.IOPS(), pr.IOPS(),
			latRatio, ctxPr, ctxUr)
	}
}

func writeSummary(p func(string, ...any), cases []benchCase) {
	var bestUringAdvQD int
	var bestUringAdvRatio float64

	var bestPreadQD int
	var bestPreadRatio float64

	for _, c := range cases {
		if c.Pread == nil || c.Uring == nil {
			continue
		}
		ratio := c.Uring.IOPS() / c.Pread.IOPS()
		if ratio > bestUringAdvRatio {
			bestUringAdvRatio = ratio
			bestUringAdvQD = c.QD
		}
		if ratio < bestPreadRatio || bestPreadRatio == 0 {
			bestPreadRatio = ratio
			bestPreadQD = c.QD
		}
	}

	if bestUringAdvRatio > 1.0 {
		p("- **io_uring shines at QD=%d** with **%.2fx** IOPS over pread. "+
			"High queue depths expose the batched submission advantage.",
			bestUringAdvQD, bestUringAdvRatio)
	}
	if bestPreadRatio > 0 && bestPreadRatio <= 1.0 {
		p("- **pread competitive at QD=%d** (ratio %.2fx). "+
			"At low concurrency the syscall overhead difference is minimal.",
			bestPreadQD, bestPreadRatio)
	}
	if bestUringAdvRatio == 0 && bestPreadRatio == 0 {
		p("- No direct comparison available (io_uring results missing).")
	}
}
